package domain;

public enum MugimenduMota {
	DIRU_SARRERA,
	DIRU_IRTEERA,
	ERRESERBA_SORTU,
	ERRESERBA_ONARTU_GIDARI,
	ERRESERBA_ONARTU_BIDAIARI,
	ERRESERBA_UKATU,
	BIDAIA_KANTZELATU_GIDARI,
	BIDAIA_KANTZELATU_BIDAIARI,
	ERRESERBA_BAIEZTATU,
	ERRESERBA_EZEZTATU_GIDARI,
	ERRESERBA_EZEZTATU_BIDAIARI
}
